language: go
go:
- master
services:
- docker
install:
- go get ./api/vendor/database
- go get ./api
script:
- cd ./api
- go test
- cd ..
after_success:
- docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
- docker build ./api -t mcmenemy/aws-auto-deploy-api:latest
- docker push mcmenemy/aws-auto-deploy-api:latest
- docker build ./frontend -t mcmenemy/aws-auto-deploy-frontend:latest
- docker push mcmenemy/aws-auto-deploy-frontend:latest
- docker build ./db -t mcmenemy/aws-auto-deploy-db:latest
- docker push mcmenemy/aws-auto-deploy-db:latest
